///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Cottbus_3000CR.Modules.STANDARD.Monitoring.Monitoring
{
    public partial class Monitoring_pruefen
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CheckTrafficOK()
        {

        	// get objects
        	
        	
        	var overviewInfo= repo.TicketingInside_DImasPlus.ContentPage.Monitoring.Monitoring.MonitoringDetails.overview.SelfInfo;
        	
        	
        	
        	RxPath rxp=overviewInfo.FindAdapter<DivTag>().GetPath();
        	string path = rxp.ToString()+"/div/div[3]/div/div[1]/div/div/div[3]";
        	

        	Validate.Exists(path,1000,"Die Ampel zeigt grün!");
   
        	
        	
        	
        	
        }



 

    }
}
