///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Cottbus_3000CR.TEST
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Versuch1()
        {

        	Report.Log(ReportLevel.Info, "INFO","ProjectName: "+TestSuite.Current.Parameters["ProjectName"]); 
        	
        	
        	foreach (string Key in TestSuite.Current.CurrentTestContainer.Parameters.Keys )
        			{
        		Report.Log(ReportLevel.Info, "INFO","keys: "+Key+ " -- " +TestSuite.CurrentTestContainer.Parameters[Key]); 
        	}
        	
        	
        	
        	
        	
        }

    }
}
