///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Cottbus_3000CR.Modules.STANDARD.Auswertung.Verkaufsdaten
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Quittungen_validieren recording.
    /// </summary>
    [TestModule("59f3f847-b53e-401c-8c82-c30d3d7ef6eb", ModuleType.Recording, 1)]
    public partial class Quittungen_validieren : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Cottbus_3000CR.HGS repository.
        /// </summary>
        public static global::Cottbus_3000CR.HGS repo = global::Cottbus_3000CR.HGS.Instance;

        static Quittungen_validieren instance = new Quittungen_validieren();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Quittungen_validieren()
        {
            VerkaufsZeitraum = "Dieser Monat";
            AutomatenNr = "";
            AbrechnungsNr = "{NumPad0}{NumPad0}{NumPad0}";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Quittungen_validieren Instance
        {
            get { return instance; }
        }

#region Variables

        string _VerkaufsZeitraum;

        /// <summary>
        /// Gets or sets the value of variable VerkaufsZeitraum.
        /// </summary>
        [TestVariable("b9e265f3-e384-4e22-be2e-8726cb81c601")]
        public string VerkaufsZeitraum
        {
            get { return _VerkaufsZeitraum; }
            set { _VerkaufsZeitraum = value; }
        }

        string _AutomatenNr;

        /// <summary>
        /// Gets or sets the value of variable AutomatenNr.
        /// </summary>
        [TestVariable("e044aab2-cde9-490f-bf0b-7351d7f0cb0f")]
        public string AutomatenNr
        {
            get { return _AutomatenNr; }
            set { _AutomatenNr = value; }
        }

        string _AbrechnungsNr;

        /// <summary>
        /// Gets or sets the value of variable AbrechnungsNr.
        /// </summary>
        [TestVariable("942721cb-05ed-4c9e-a701-7bc473471f6f")]
        public string AbrechnungsNr
        {
            get { return _AbrechnungsNr; }
            set { _AbrechnungsNr = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Menue
            Report.Log(ReportLevel.Info, "Section", "Menue", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.Menue.Verkaufsdaten' at 56;10.", repo.TicketingInside_DImasPlus.Menue.VerkaufsdatenInfo, new RecordItemIndex(1));
            repo.TicketingInside_DImasPlus.Menue.Verkaufsdaten.Click("56;10");
            Delay.Milliseconds(0);
            
            // Navigation
            Report.Log(ReportLevel.Info, "Section", "Navigation", new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Tabs.Quittungen' at 49;15.", repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Tabs.QuittungenInfo, new RecordItemIndex(3));
            repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Tabs.Quittungen.Click("49;15");
            Delay.Milliseconds(0);
            
            // Verkaufszeitraum
            Report.Log(ReportLevel.Info, "Section", "Verkaufszeitraum", new RecordItemIndex(4));
            
            UserCodeCollections.DPlusLibrary.setTimePeriod(repo.TicketingInside_DImasPlus.PopUps.SelfInfo, repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Verkaufszeitraum.btnKalenderInfo, VerkaufsZeitraum);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(6));
            Delay.Duration(500, false);
            
            // Filtern
            Report.Log(ReportLevel.Info, "Section", "Filtern", new RecordItemIndex(7));
            
            UserCodeCollections.DPlusLibrary.Fill_textfilter(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Quittungen.Tabelle.Filter.FilterGeraeteNrInfo, AutomatenNr);
            Delay.Milliseconds(0);
            
            UserCodeCollections.DPlusLibrary.Fill_textfilter(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Quittungen.Tabelle.Filter.FilterAbrechnungsNrInfo, AbrechnungsNr);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(10));
            Delay.Duration(500, false);
            
            // Validierung
            Report.Log(ReportLevel.Info, "Section", "Validierung", new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AutomatenNr) on item 'TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Quittungen.Tabelle.Zeile1.cellGeraeteNr'.", repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Quittungen.Tabelle.Zeile1.cellGeraeteNrInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Quittungen.Tabelle.Zeile1.cellGeraeteNrInfo, "InnerText", AutomatenNr);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AbrechnungsNr) on item 'TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Quittungen.Tabelle.Zeile1.cellAbrechnungsNr'.", repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Quittungen.Tabelle.Zeile1.cellAbrechnungsNrInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Quittungen.Tabelle.Zeile1.cellAbrechnungsNrInfo, "InnerText", AbrechnungsNr);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(14));
            Delay.Duration(300, false);
            
            Validate_Quittungentable(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Verkaufsdaten.Quittungen.Tabelle.Zeile1.SelfInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
