///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Cottbus_3000CR.Modules.STANDARD.Monitoring.Geldspeicherinhalt
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Geldspeicherinhalt_pruefen recording.
    /// </summary>
    [TestModule("d903627b-7656-48f3-9ea6-4a7356715e49", ModuleType.Recording, 1)]
    public partial class Geldspeicherinhalt_pruefen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Cottbus_3000CR.HGS repository.
        /// </summary>
        public static global::Cottbus_3000CR.HGS repo = global::Cottbus_3000CR.HGS.Instance;

        static Geldspeicherinhalt_pruefen instance = new Geldspeicherinhalt_pruefen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Geldspeicherinhalt_pruefen()
        {
            AutomatenNr = "";
            AbrechnungsNr = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Geldspeicherinhalt_pruefen Instance
        {
            get { return instance; }
        }

#region Variables

        string _AutomatenNr;

        /// <summary>
        /// Gets or sets the value of variable AutomatenNr.
        /// </summary>
        [TestVariable("e1a8687f-cc9b-4c99-96c7-ea75a0c85f30")]
        public string AutomatenNr
        {
            get { return _AutomatenNr; }
            set { _AutomatenNr = value; }
        }

        string _AbrechnungsNr;

        /// <summary>
        /// Gets or sets the value of variable AbrechnungsNr.
        /// </summary>
        [TestVariable("0d25fc74-ed3e-49e0-93dc-fd856b49dc28")]
        public string AbrechnungsNr
        {
            get { return _AbrechnungsNr; }
            set { _AbrechnungsNr = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // navigiere zu Geldspeicher
            Report.Log(ReportLevel.Info, "Section", "navigiere zu Geldspeicher", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.Menue.Geldspeicherinhalt' at Center.", repo.TicketingInside_DImasPlus.Menue.GeldspeicherinhaltInfo, new RecordItemIndex(1));
            repo.TicketingInside_DImasPlus.Menue.Geldspeicherinhalt.Click();
            Delay.Milliseconds(0);
            
            // Filter einstellen
            Report.Log(ReportLevel.Info, "Section", "Filter einstellen", new RecordItemIndex(2));
            
            UserCodeCollections.DPlusLibrary.Fill_textfilter(repo.TicketingInside_DImasPlus.ContentPage.Monitoring.Geldspeicherinhalt.Tabelle.Filter.filterGeraetenummerInfo, AutomatenNr);
            Delay.Milliseconds(0);
            
            UserCodeCollections.DPlusLibrary.Fill_textfilter(repo.TicketingInside_DImasPlus.ContentPage.Monitoring.Geldspeicherinhalt.Tabelle.Filter.filterAberchnungsnummerInfo, AbrechnungsNr);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(5));
            Delay.Duration(300, false);
            
            validateGeldspeicherinhalt(repo.TicketingInside_DImasPlus.ContentPage.Monitoring.Geldspeicherinhalt.Tabelle.Zeile1.SelfInfo);
            Delay.Milliseconds(0);
            
            // navigiere zu den details
            Report.Log(ReportLevel.Info, "Section", "navigiere zu den details", new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.ContentPage.Monitoring.Geldspeicherinhalt.Tabelle.Zeile1.cellGeraetenummer' at Center.", repo.TicketingInside_DImasPlus.ContentPage.Monitoring.Geldspeicherinhalt.Tabelle.Zeile1.cellGeraetenummerInfo, new RecordItemIndex(8));
            repo.TicketingInside_DImasPlus.ContentPage.Monitoring.Geldspeicherinhalt.Tabelle.Zeile1.cellGeraetenummer.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$AutomatenNr) on item 'TicketingInside_DImasPlus.ContentPage.Monitoring.Geldspeicherinhalt.GeldspeicherinhaltDetails.lblTitle'.", repo.TicketingInside_DImasPlus.ContentPage.Monitoring.Geldspeicherinhalt.GeldspeicherinhaltDetails.lblTitleInfo, new RecordItemIndex(9));
            Validate.AttributeContains(repo.TicketingInside_DImasPlus.ContentPage.Monitoring.Geldspeicherinhalt.GeldspeicherinhaltDetails.lblTitleInfo, "InnerText", AutomatenNr);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
