///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Cottbus_3000CR.Modules.STANDARD.HauptDisplay
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DialogStrukturValidierung recording.
    /// </summary>
    [TestModule("082cbe7a-4483-4641-b0be-741815340527", ModuleType.Recording, 1)]
    public partial class DialogStrukturValidierung : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Cottbus_3000CR.HGS repository.
        /// </summary>
        public static global::Cottbus_3000CR.HGS repo = global::Cottbus_3000CR.HGS.Instance;

        static DialogStrukturValidierung instance = new DialogStrukturValidierung();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DialogStrukturValidierung()
        {
            MainMenueName = "";
            DLGTitel = "";
            DLGTabAnzahl = "";
            DLGButtonName = "";
            DLGTableTyp = "";
            DLGTableButtons = "";
            DLGTabNames = "";
            SubMenueName = "";
            DLGZeitraumauswahl = "";
            DLGTableColAuswahl = "";
            TabulatorName = "";
            DLGTable2Buttons = "";
            DLGTable2ColAuswahl = "";
            DLGSubDlg = "";
            DLGSubDlgTitel = "";
            DLGSubDlgLabels = "";
            DLGSubDlgTabellenTyp = "";
            DLGSubDlgTButtons = "";
            DLGSubDlgTSpaltenAuswahl = "";
            DLGSubDlgT2Buttons = "";
            DLGSubDlgT2SpaltenAuswahl = "";
            DLGLabels = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DialogStrukturValidierung Instance
        {
            get { return instance; }
        }

#region Variables

        string _MainMenueName;

        /// <summary>
        /// Gets or sets the value of variable MainMenueName.
        /// </summary>
        [TestVariable("44b3c6c5-2c59-4e30-9590-313f869171b4")]
        public string MainMenueName
        {
            get { return _MainMenueName; }
            set { _MainMenueName = value; }
        }

        string _DLGTitel;

        /// <summary>
        /// Gets or sets the value of variable DLGTitel.
        /// </summary>
        [TestVariable("f26eddd8-06e8-4bf0-8335-9825df11d170")]
        public string DLGTitel
        {
            get { return _DLGTitel; }
            set { _DLGTitel = value; }
        }

        string _DLGTabAnzahl;

        /// <summary>
        /// Gets or sets the value of variable DLGTabAnzahl.
        /// </summary>
        [TestVariable("1a78da4e-45f7-4444-adeb-b0ae6f6a3312")]
        public string DLGTabAnzahl
        {
            get { return _DLGTabAnzahl; }
            set { _DLGTabAnzahl = value; }
        }

        string _DLGButtonName;

        /// <summary>
        /// Gets or sets the value of variable DLGButtonName.
        /// </summary>
        [TestVariable("ceff555d-cb99-4ca3-a80c-34f8c0f02ef4")]
        public string DLGButtonName
        {
            get { return _DLGButtonName; }
            set { _DLGButtonName = value; }
        }

        string _DLGTableTyp;

        /// <summary>
        /// Gets or sets the value of variable DLGTableTyp.
        /// </summary>
        [TestVariable("dffd5f29-8447-4f70-b009-d4fc8bad9381")]
        public string DLGTableTyp
        {
            get { return _DLGTableTyp; }
            set { _DLGTableTyp = value; }
        }

        string _DLGTableButtons;

        /// <summary>
        /// Gets or sets the value of variable DLGTableButtons.
        /// </summary>
        [TestVariable("c7f313a3-7332-47e3-87f4-7969ba4f3ff5")]
        public string DLGTableButtons
        {
            get { return _DLGTableButtons; }
            set { _DLGTableButtons = value; }
        }

        string _DLGTabNames;

        /// <summary>
        /// Gets or sets the value of variable DLGTabNames.
        /// </summary>
        [TestVariable("d0f95dd7-7085-4e94-aa70-fec2ff9632c6")]
        public string DLGTabNames
        {
            get { return _DLGTabNames; }
            set { _DLGTabNames = value; }
        }

        string _SubMenueName;

        /// <summary>
        /// Gets or sets the value of variable SubMenueName.
        /// </summary>
        [TestVariable("5770d5a9-ba73-49ce-bd3f-3b7c2ee808c1")]
        public string SubMenueName
        {
            get { return _SubMenueName; }
            set { _SubMenueName = value; }
        }

        string _DLGZeitraumauswahl;

        /// <summary>
        /// Gets or sets the value of variable DLGZeitraumauswahl.
        /// </summary>
        [TestVariable("c9c9e66f-de61-49d7-bb1c-44d652339b56")]
        public string DLGZeitraumauswahl
        {
            get { return _DLGZeitraumauswahl; }
            set { _DLGZeitraumauswahl = value; }
        }

        string _DLGTableColAuswahl;

        /// <summary>
        /// Gets or sets the value of variable DLGTableColAuswahl.
        /// </summary>
        [TestVariable("833c55a1-9eb2-4508-9c85-fbd66a53de31")]
        public string DLGTableColAuswahl
        {
            get { return _DLGTableColAuswahl; }
            set { _DLGTableColAuswahl = value; }
        }

        string _TabulatorName;

        /// <summary>
        /// Gets or sets the value of variable TabulatorName.
        /// </summary>
        [TestVariable("8fa81508-70b2-497e-9ee1-bc99a355c439")]
        public string TabulatorName
        {
            get { return _TabulatorName; }
            set { _TabulatorName = value; }
        }

        string _DLGTable2Buttons;

        /// <summary>
        /// Gets or sets the value of variable DLGTable2Buttons.
        /// </summary>
        [TestVariable("5958c630-38d7-4fd6-8f70-07cebff8e75b")]
        public string DLGTable2Buttons
        {
            get { return _DLGTable2Buttons; }
            set { _DLGTable2Buttons = value; }
        }

        string _DLGTable2ColAuswahl;

        /// <summary>
        /// Gets or sets the value of variable DLGTable2ColAuswahl.
        /// </summary>
        [TestVariable("318df43f-3dd1-4bc9-9df8-14d9a4cf592a")]
        public string DLGTable2ColAuswahl
        {
            get { return _DLGTable2ColAuswahl; }
            set { _DLGTable2ColAuswahl = value; }
        }

        string _DLGSubDlg;

        /// <summary>
        /// Gets or sets the value of variable DLGSubDlg.
        /// </summary>
        [TestVariable("4787ed24-1efb-4bf2-ad67-aeb02ddfe672")]
        public string DLGSubDlg
        {
            get { return _DLGSubDlg; }
            set { _DLGSubDlg = value; }
        }

        string _DLGSubDlgTitel;

        /// <summary>
        /// Gets or sets the value of variable DLGSubDlgTitel.
        /// </summary>
        [TestVariable("4d5b4c8c-43f4-4398-aee1-234989a8ca36")]
        public string DLGSubDlgTitel
        {
            get { return _DLGSubDlgTitel; }
            set { _DLGSubDlgTitel = value; }
        }

        string _DLGSubDlgLabels;

        /// <summary>
        /// Gets or sets the value of variable DLGSubDlgLabels.
        /// </summary>
        [TestVariable("2147b89e-9010-48d7-8b0a-d6ba7895ce4a")]
        public string DLGSubDlgLabels
        {
            get { return _DLGSubDlgLabels; }
            set { _DLGSubDlgLabels = value; }
        }

        string _DLGSubDlgTabellenTyp;

        /// <summary>
        /// Gets or sets the value of variable DLGSubDlgTabellenTyp.
        /// </summary>
        [TestVariable("4bdfddc3-c768-472b-998c-d714e2829099")]
        public string DLGSubDlgTabellenTyp
        {
            get { return _DLGSubDlgTabellenTyp; }
            set { _DLGSubDlgTabellenTyp = value; }
        }

        string _DLGSubDlgTButtons;

        /// <summary>
        /// Gets or sets the value of variable DLGSubDlgTButtons.
        /// </summary>
        [TestVariable("4e59e9f1-badd-4ef3-a057-023e10a7d5ee")]
        public string DLGSubDlgTButtons
        {
            get { return _DLGSubDlgTButtons; }
            set { _DLGSubDlgTButtons = value; }
        }

        string _DLGSubDlgTSpaltenAuswahl;

        /// <summary>
        /// Gets or sets the value of variable DLGSubDlgTSpaltenAuswahl.
        /// </summary>
        [TestVariable("1da6f06f-2847-4467-9d4a-af8c691a8f3d")]
        public string DLGSubDlgTSpaltenAuswahl
        {
            get { return _DLGSubDlgTSpaltenAuswahl; }
            set { _DLGSubDlgTSpaltenAuswahl = value; }
        }

        string _DLGSubDlgT2Buttons;

        /// <summary>
        /// Gets or sets the value of variable DLGSubDlgT2Buttons.
        /// </summary>
        [TestVariable("f4302b04-0bab-4269-acf5-c686e08096c6")]
        public string DLGSubDlgT2Buttons
        {
            get { return _DLGSubDlgT2Buttons; }
            set { _DLGSubDlgT2Buttons = value; }
        }

        string _DLGSubDlgT2SpaltenAuswahl;

        /// <summary>
        /// Gets or sets the value of variable DLGSubDlgT2SpaltenAuswahl.
        /// </summary>
        [TestVariable("01c94d72-9daf-4a44-bd11-2bf32837df3d")]
        public string DLGSubDlgT2SpaltenAuswahl
        {
            get { return _DLGSubDlgT2SpaltenAuswahl; }
            set { _DLGSubDlgT2SpaltenAuswahl = value; }
        }

        string _DLGLabels;

        /// <summary>
        /// Gets or sets the value of variable DLGLabels.
        /// </summary>
        [TestVariable("ac473010-f75b-4acd-9301-a16d19f8cc7b")]
        public string DLGLabels
        {
            get { return _DLGLabels; }
            set { _DLGLabels = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // MenueItem auswählen
            Report.Log(ReportLevel.Info, "Section", "MenueItem auswählen", new RecordItemIndex(0));
            
            try {
                clickOnMenueItem(repo.TicketingInside_DImasPlus.Menue.SelfInfo, MainMenueName, SubMenueName);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 800ms.", new RecordItemIndex(2));
            Delay.Duration(800, false);
            
            clickOnTab(TabulatorName);
            Delay.Milliseconds(0);
            
            // Struktur prüfung
            Report.Log(ReportLevel.Info, "Section", "Struktur prüfung", new RecordItemIndex(4));
            
            try {
                checkTitel(DLGTitel, DLGLabels);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            try {
                checkTabulatoren(DLGTabAnzahl, DLGTabNames);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            try {
                checkButton(DLGButtonName);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            try {
                checkZeitrtaum(DLGZeitraumauswahl);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
            try {
                checkTableStruktur(DLGTableTyp, DLGTableButtons, DLGTableColAuswahl, DLGTable2Buttons, DLGTable2ColAuswahl);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
            try {
                checkforSubDialog(DLGSubDlg, DLGSubDlgTitel, DLGSubDlgLabels, DLGSubDlgTabellenTyp, DLGSubDlgTButtons, DLGSubDlgTSpaltenAuswahl, DLGSubDlgT2Buttons, DLGSubDlgT2SpaltenAuswahl);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(10)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
