///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Cottbus_3000CR.Modules.STANDARD.HauptDisplay
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MenuValidierung recording.
    /// </summary>
    [TestModule("e08c0edb-321b-4a73-ba43-273c179e7310", ModuleType.Recording, 1)]
    public partial class MenuValidierung : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Cottbus_3000CR.HGS repository.
        /// </summary>
        public static global::Cottbus_3000CR.HGS repo = global::Cottbus_3000CR.HGS.Instance;

        static MenuValidierung instance = new MenuValidierung();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MenuValidierung()
        {
            MenueItemName = "";
            MenueLevel = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MenuValidierung Instance
        {
            get { return instance; }
        }

#region Variables

        string _MenueItemName;

        /// <summary>
        /// Gets or sets the value of variable MenueItemName.
        /// </summary>
        [TestVariable("9bb68f6d-1ea1-42f3-afce-0c7ce81f9040")]
        public string MenueItemName
        {
            get { return _MenueItemName; }
            set { _MenueItemName = value; }
        }

        string _MenueLevel;

        /// <summary>
        /// Gets or sets the value of variable MenueLevel.
        /// </summary>
        [TestVariable("c8ffcd08-032c-4476-9f8d-f05019d5cd34")]
        public string MenueLevel
        {
            get { return _MenueLevel; }
            set { _MenueLevel = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            validateMenueItem(MenueItemName, MenueLevel, repo.TicketingInside_DImasPlus.Menue.SelfInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
