///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Cottbus_3000CR.Modules.STANDARD.Auswertung.Abrechnungen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Abrechnungsluecken_validieren recording.
    /// </summary>
    [TestModule("af50d4fd-37bd-4c68-ae53-0457e12d4bce", ModuleType.Recording, 1)]
    public partial class Abrechnungsluecken_validieren : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Cottbus_3000CR.HGS repository.
        /// </summary>
        public static global::Cottbus_3000CR.HGS repo = global::Cottbus_3000CR.HGS.Instance;

        static Abrechnungsluecken_validieren instance = new Abrechnungsluecken_validieren();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Abrechnungsluecken_validieren()
        {
            Automatennummer = "999000";
            Abrechnungsnummer = "10018";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Abrechnungsluecken_validieren Instance
        {
            get { return instance; }
        }

#region Variables

        string _Automatennummer;

        /// <summary>
        /// Gets or sets the value of variable Automatennummer.
        /// </summary>
        [TestVariable("1c5a430c-8438-49c9-b410-0a1d222127e6")]
        public string Automatennummer
        {
            get { return _Automatennummer; }
            set { _Automatennummer = value; }
        }

        string _Abrechnungsnummer;

        /// <summary>
        /// Gets or sets the value of variable Abrechnungsnummer.
        /// </summary>
        [TestVariable("a724169c-45bf-4769-872d-b59f89131ccf")]
        public string Abrechnungsnummer
        {
            get { return _Abrechnungsnummer; }
            set { _Abrechnungsnummer = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Abrechnungslücken
            Report.Log(ReportLevel.Info, "Section", "Abrechnungslücken", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(1));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAberAbrluecken' at Center.", repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAberAbrlueckenInfo, new RecordItemIndex(2));
            repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAberAbrluecken.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(3));
            Delay.Duration(300, false);
            
            // Filtern
            Report.Log(ReportLevel.Info, "Section", "Filtern", new RecordItemIndex(4));
            
            UserCodeCollections.DPlusLibrary.Fill_textfilter(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.TableFilter.filterAutomatenNrInfo, Automatennummer);
            Delay.Milliseconds(0);
            
            UserCodeCollections.DPlusLibrary.Fill_textfilter(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.TableFilter.filterAbrechnungsNrInfo, Abrechnungsnummer);
            Delay.Milliseconds(0);
            
            // Abrechnungslücken prüfen
            Report.Log(ReportLevel.Info, "Section", "Abrechnungslücken prüfen", new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$Automatennummer) on item 'TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellGeraetenummer'.", repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellGeraetenummerInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellGeraetenummerInfo, "InnerText", Automatennummer);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$Abrechnungsnummer) on item 'TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellNachfAbrechn_ungsnr'.", repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellNachfAbrechn_ungsnrInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellNachfAbrechn_ungsnrInfo, "InnerText", Abrechnungsnummer);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Offen') on item 'TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellStatus'.", repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellStatusInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellStatusInfo, "InnerText", "Offen");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Quittieren') on item 'TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellAktionen'.", repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellAktionenInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.Abrechnungsluecken.Table_Luecke.cellAktionenInfo, "InnerText", "Quittieren");
            Delay.Milliseconds(100);
            
            // zurück
            Report.Log(ReportLevel.Info, "Section", "zurück", new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAbrAbrechnung' at Center.", repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAbrAbrechnungInfo, new RecordItemIndex(13));
            repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAbrAbrechnung.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
