///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Cottbus_3000CR.Modules.STANDARD.Auswertung.Abrechnungen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Schicht_Stoerbetrag_quittieren recording.
    /// </summary>
    [TestModule("4ad2d11a-c832-48ee-9734-baa3cbbe9d66", ModuleType.Recording, 1)]
    public partial class Schicht_Stoerbetrag_quittieren : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Cottbus_3000CR.HGS repository.
        /// </summary>
        public static global::Cottbus_3000CR.HGS repo = global::Cottbus_3000CR.HGS.Instance;

        static Schicht_Stoerbetrag_quittieren instance = new Schicht_Stoerbetrag_quittieren();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Schicht_Stoerbetrag_quittieren()
        {
            Automatennummer = "999000";
            Abrechnungsnummer = "10018";
            FehlendeAbrechnungsNr = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Schicht_Stoerbetrag_quittieren Instance
        {
            get { return instance; }
        }

#region Variables

        string _Automatennummer;

        /// <summary>
        /// Gets or sets the value of variable Automatennummer.
        /// </summary>
        [TestVariable("1db1969a-a774-469c-8865-584ffca524da")]
        public string Automatennummer
        {
            get { return _Automatennummer; }
            set { _Automatennummer = value; }
        }

        string _Abrechnungsnummer;

        /// <summary>
        /// Gets or sets the value of variable Abrechnungsnummer.
        /// </summary>
        [TestVariable("4bf050c6-048b-4e76-8755-1ece989b23d7")]
        public string Abrechnungsnummer
        {
            get { return _Abrechnungsnummer; }
            set { _Abrechnungsnummer = value; }
        }

        string _FehlendeAbrechnungsNr;

        /// <summary>
        /// Gets or sets the value of variable FehlendeAbrechnungsNr.
        /// </summary>
        [TestVariable("e5e14a32-5290-4227-b120-69137b12df61")]
        public string FehlendeAbrechnungsNr
        {
            get { return _FehlendeAbrechnungsNr; }
            set { _FehlendeAbrechnungsNr = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAberAbrluecken' at Center.", repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAberAbrlueckenInfo, new RecordItemIndex(0));
            repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAberAbrluecken.Click();
            Delay.Milliseconds(0);
            
            // Abrechnungslücken
            Report.Log(ReportLevel.Info, "Section", "Abrechnungslücken", new RecordItemIndex(1));
            
            UserCodeCollections.DPlusLibrary.Fill_textfilter(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.TableFilter.filterAutomatenNrInfo, Automatennummer);
            Delay.Milliseconds(0);
            
            UserCodeCollections.DPlusLibrary.Fill_textfilter(repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.TableFilter.filterNachfolgendeAbrechnungInfo, Abrechnungsnummer);
            Delay.Milliseconds(0);
            
            // Abrechnungslücken Abrechnungsnr holen
            Report.Log(ReportLevel.Info, "Section", "Abrechnungslücken Abrechnungsnr holen", new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'Abrechnungsluecken.Table_Luecke.cellFehlendeAbrechnung' and assigning its value to variable 'FehlendeAbrechnungsNr'.", repo.Abrechnungsluecken.Table_Luecke.cellFehlendeAbrechnungInfo, new RecordItemIndex(5));
            FehlendeAbrechnungsNr = repo.Abrechnungsluecken.Table_Luecke.cellFehlendeAbrechnung.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Abrechnungsluecken.Table_Luecke.cellAktionen' at Center.", repo.Abrechnungsluecken.Table_Luecke.cellAktionenInfo, new RecordItemIndex(6));
            repo.Abrechnungsluecken.Table_Luecke.cellAktionen.Click();
            Delay.Milliseconds(0);
            
            // Pop-up
            Report.Log(ReportLevel.Info, "Section", "Pop-up", new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(8));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'Abrechnung') on item 'TicketingInside_DImasPlus.PopUps.Quittieren.tlblTitel'.", repo.TicketingInside_DImasPlus.PopUps.Quittieren.tlblTitelInfo, new RecordItemIndex(9));
            Validate.AttributeContains(repo.TicketingInside_DImasPlus.PopUps.Quittieren.tlblTitelInfo, "InnerText", "Abrechnung");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$FehlendeAbrechnungsNr) on item 'TicketingInside_DImasPlus.PopUps.Quittieren.tlblTitel'.", repo.TicketingInside_DImasPlus.PopUps.Quittieren.tlblTitelInfo, new RecordItemIndex(10));
            Validate.AttributeContains(repo.TicketingInside_DImasPlus.PopUps.Quittieren.tlblTitelInfo, "InnerText", FehlendeAbrechnungsNr);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'quittieren') on item 'TicketingInside_DImasPlus.PopUps.Quittieren.tlblTitel'.", repo.TicketingInside_DImasPlus.PopUps.Quittieren.tlblTitelInfo, new RecordItemIndex(11));
            Validate.AttributeContains(repo.TicketingInside_DImasPlus.PopUps.Quittieren.tlblTitelInfo, "InnerText", "quittieren");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'Möchten Sie die fehlende Abrechnung quittieren?') on item 'TicketingInside_DImasPlus.PopUps.Quittieren.lblNachricht'.", repo.TicketingInside_DImasPlus.PopUps.Quittieren.lblNachrichtInfo, new RecordItemIndex(12));
            Validate.AttributeContains(repo.TicketingInside_DImasPlus.PopUps.Quittieren.lblNachrichtInfo, "InnerText", "Möchten Sie die fehlende Abrechnung quittieren?");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Alles ist richtig so.' with focus on 'TicketingInside_DImasPlus.PopUps.Quittieren.txtBegruendung'.", repo.TicketingInside_DImasPlus.PopUps.Quittieren.txtBegruendungInfo, new RecordItemIndex(13));
            repo.TicketingInside_DImasPlus.PopUps.Quittieren.txtBegruendung.PressKeys("Alles ist richtig so.");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.PopUps.Quittieren.btnBestaetigen' at Center.", repo.TicketingInside_DImasPlus.PopUps.Quittieren.btnBestaetigenInfo, new RecordItemIndex(14));
            repo.TicketingInside_DImasPlus.PopUps.Quittieren.btnBestaetigen.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAbrAbrechnung' at Center.", repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAbrAbrechnungInfo, new RecordItemIndex(15));
            repo.TicketingInside_DImasPlus.ContentPage.Auswertung.Abrechnungen.btnAbrAbrechnung.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
