///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Cottbus_3000CR.Modules.STANDARD.Papierrollenverwaltung.Papierrollen
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Papierrollen_validierung recording.
    /// </summary>
    [TestModule("a6f30e07-5750-493c-843c-436642d5cbe5", ModuleType.Recording, 1)]
    public partial class Papierrollen_validierung : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Cottbus_3000CR.HGS repository.
        /// </summary>
        public static global::Cottbus_3000CR.HGS repo = global::Cottbus_3000CR.HGS.Instance;

        static Papierrollen_validierung instance = new Papierrollen_validierung();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Papierrollen_validierung()
        {
            Seriennummer = "99009901";
            AutomatenNr = "999000";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Papierrollen_validierung Instance
        {
            get { return instance; }
        }

#region Variables

        string _Seriennummer;

        /// <summary>
        /// Gets or sets the value of variable Seriennummer.
        /// </summary>
        [TestVariable("e7f7e550-a517-4158-b523-5487ebd7dc25")]
        public string Seriennummer
        {
            get { return _Seriennummer; }
            set { _Seriennummer = value; }
        }

        string _AutomatenNr;

        /// <summary>
        /// Gets or sets the value of variable AutomatenNr.
        /// </summary>
        [TestVariable("76042da0-c62b-4b89-8d45-f99f79e7c83d")]
        public string AutomatenNr
        {
            get { return _AutomatenNr; }
            set { _AutomatenNr = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Papierrollenübersicht
            Report.Log(ReportLevel.Info, "Section", "Papierrollenübersicht", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.Menue.Papierrollen' at 75;16.", repo.TicketingInside_DImasPlus.Menue.PapierrollenInfo, new RecordItemIndex(1));
            repo.TicketingInside_DImasPlus.Menue.Papierrollen.Click("75;16");
            Delay.Milliseconds(0);
            
            // Filtern
            Report.Log(ReportLevel.Info, "Section", "Filtern", new RecordItemIndex(2));
            
            UserCodeCollections.DPlusLibrary.Fill_textfilter(repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Filter.FilterSeriennummerInfo, Seriennummer);
            Delay.Milliseconds(0);
            
            UserCodeCollections.DPlusLibrary.Fill_textfilter(repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Filter.FilterGeraetenummerInfo, AutomatenNr);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(5));
            Delay.Duration(500, false);
            
            // Tabellenzeile validieren
            Report.Log(ReportLevel.Info, "Section", "Tabellenzeile validieren", new RecordItemIndex(6));
            
            UserCodeCollections.DPlusLibrary.validateInnertextWithXMLtag(repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellBarcodeInfo, "barcode");
            Delay.Milliseconds(0);
            
            UserCodeCollections.DPlusLibrary.validateInnertextWithXMLtag(repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellPapiersorteInfo, "papiersorte");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$Seriennummer) on item 'TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellSeriennummer'.", repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellSeriennummerInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellSeriennummerInfo, "InnerText", Seriennummer);
            Delay.Milliseconds(0);
            
            UserCodeCollections.DPlusLibrary.validateInnertextWithXMLtag(repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellAktuellerAbschnittInfo, "aktuellerabschnitt");
            Delay.Milliseconds(0);
            
            UserCodeCollections.DPlusLibrary.validateInnertextWithXMLtag(repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellVerbliebeneAbschnitteInfo, "verbleibendeabschnitte");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AutomatenNr) on item 'TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellGertaetenummer'.", repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellGertaetenummerInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellGertaetenummerInfo, "InnerText", AutomatenNr);
            Delay.Milliseconds(0);
            
            UserCodeCollections.DPlusLibrary.validateInnertextWithXMLtag(repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellStatusInfo, "status");
            Delay.Milliseconds(0);
            
            UserCodeCollections.DPlusLibrary.validateInnertextWithXMLtag(repo.TicketingInside_DImasPlus.ContentPage.Papierrollenverwaltung.Papierrollen.Tabelle.Zeile1.CellPapierbahnInfo, "baugruppentyp");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
