///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Cottbus_3000CR.Modules.STANDARD.Geraeteverwaltung.Geraete
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Geraet_Loeschen recording.
    /// </summary>
    [TestModule("8f570902-0e30-4e1c-af59-04b5e6a9d809", ModuleType.Recording, 1)]
    public partial class Geraet_Loeschen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Cottbus_3000CR.HGS repository.
        /// </summary>
        public static global::Cottbus_3000CR.HGS repo = global::Cottbus_3000CR.HGS.Instance;

        static Geraet_Loeschen instance = new Geraet_Loeschen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Geraet_Loeschen()
        {
            AutomatenNrNeu = "1111111";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Geraet_Loeschen Instance
        {
            get { return instance; }
        }

#region Variables

        string _AutomatenNrNeu;

        /// <summary>
        /// Gets or sets the value of variable AutomatenNrNeu.
        /// </summary>
        [TestVariable("152fdea0-31df-46bb-bc68-2c1ab9f9723d")]
        public string AutomatenNrNeu
        {
            get { return _AutomatenNrNeu; }
            set { _AutomatenNrNeu = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Geräte Menü auswählen
            Report.Log(ReportLevel.Info, "Section", "Geräte Menü auswählen", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.Menue.Geraete' at Center.", repo.TicketingInside_DImasPlus.Menue.GeraeteInfo, new RecordItemIndex(1));
            repo.TicketingInside_DImasPlus.Menue.Geraete.Click();
            Delay.Milliseconds(0);
            
            // Filter Gerät
            Report.Log(ReportLevel.Info, "Section", "Filter Gerät", new RecordItemIndex(2));
            
            UserCodeCollections.DPlusLibrary.Fill_textfilter(repo.TicketingInside_DImasPlus.ContentPage.Geraeteverwaltung.Geraete.Tabelle.TabellenFilter.FilterGeraetenummerInfo, AutomatenNrNeu);
            Delay.Milliseconds(0);
            
            // Löschen
            Report.Log(ReportLevel.Info, "Section", "Löschen", new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.ContentPage.Geraeteverwaltung.Geraete.Tabelle.TabellenInhalt.Zeile_1.BtnLoeschen' at Center.", repo.TicketingInside_DImasPlus.ContentPage.Geraeteverwaltung.Geraete.Tabelle.TabellenInhalt.Zeile_1.BtnLoeschenInfo, new RecordItemIndex(5));
            repo.TicketingInside_DImasPlus.ContentPage.Geraeteverwaltung.Geraete.Tabelle.TabellenInhalt.Zeile_1.BtnLoeschen.Click();
            Delay.Milliseconds(0);
            
            // Pop-up
            Report.Log(ReportLevel.Info, "Section", "Pop-up", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(7));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'Löschen') on item 'TicketingInside_DImasPlus.PopUps.LoeschenGeraet.tlblTitel'.", repo.TicketingInside_DImasPlus.PopUps.LoeschenGeraet.tlblTitelInfo, new RecordItemIndex(8));
            Validate.AttributeContains(repo.TicketingInside_DImasPlus.PopUps.LoeschenGeraet.tlblTitelInfo, "InnerText", "Löschen");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'Möchten Sie') on item 'TicketingInside_DImasPlus.PopUps.LoeschenGeraet.lblNachricht'.", repo.TicketingInside_DImasPlus.PopUps.LoeschenGeraet.lblNachrichtInfo, new RecordItemIndex(9));
            Validate.AttributeContains(repo.TicketingInside_DImasPlus.PopUps.LoeschenGeraet.lblNachrichtInfo, "InnerText", "Möchten Sie");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$AutomatenNrNeu) on item 'TicketingInside_DImasPlus.PopUps.LoeschenGeraet.lblNachricht'.", repo.TicketingInside_DImasPlus.PopUps.LoeschenGeraet.lblNachrichtInfo, new RecordItemIndex(10));
            Validate.AttributeContains(repo.TicketingInside_DImasPlus.PopUps.LoeschenGeraet.lblNachrichtInfo, "InnerText", AutomatenNrNeu);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'wirklich löschen?') on item 'TicketingInside_DImasPlus.PopUps.LoeschenGeraet.lblNachricht'.", repo.TicketingInside_DImasPlus.PopUps.LoeschenGeraet.lblNachrichtInfo, new RecordItemIndex(11));
            Validate.AttributeContains(repo.TicketingInside_DImasPlus.PopUps.LoeschenGeraet.lblNachrichtInfo, "InnerText", "wirklich löschen?");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TicketingInside_DImasPlus.PopUps.LoeschenGeraet.btnBestaetigen' at Center.", repo.TicketingInside_DImasPlus.PopUps.LoeschenGeraet.btnBestaetigenInfo, new RecordItemIndex(12));
            repo.TicketingInside_DImasPlus.PopUps.LoeschenGeraet.btnBestaetigen.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
